import { Footer, Navbar } from "@/components";
import "./globals.css";

export const metadata = {
  title: "Market",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
